# Generated by Django 5.2.7 on 2025-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielanguages',
            name='languages_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='languages_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
