# Generated by Django 5.2.7 on 2025-11-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movielanguages_languages_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_frames', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_videos', to='movie_app.movie'),
        ),
    ]
