# Generated by Django 5.2.7 on 2025-11-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_moments_movie_alter_movielanguages_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movie_app.movie'),
        ),
    ]
